# Generated by Django 3.0.3 on 2020-10-16 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200921_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='Status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('New_Request', 'New_Request'), ('Resubmission', 'Resubmission'), ('On-Going', 'On-Going'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Completed', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('middlename', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
