# Generated by Django 3.0.3 on 2020-10-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201016_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='profile_image/'),
        ),
    ]
